import math
import torch
import torch.nn as nn
import torch.nn.functional as F

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (torch.Tensor, float, float, float, float) -> torch.Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds.
    """
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        import warnings
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

class RLN(nn.Module):
    r"""Revised LayerNorm from MPMF-Net"""
    def __init__(self, dim, eps=1e-5, detach_grad=False):
        super(RLN, self).__init__()
        self.eps = eps
        self.detach_grad = detach_grad

        self.weight = nn.Parameter(torch.ones((1, dim, 1, 1)))
        self.bias = nn.Parameter(torch.zeros((1, dim, 1, 1)))

        self.meta1 = nn.Conv2d(1, dim, 1)
        self.meta2 = nn.Conv2d(1, dim, 1)

        trunc_normal_(self.meta1.weight, std=.02)
        nn.init.constant_(self.meta1.bias, 1)

        trunc_normal_(self.meta2.weight, std=.02)
        nn.init.constant_(self.meta2.bias, 0)

    def forward(self, input):
        mean = torch.mean(input, dim=(1, 2, 3), keepdim=True)
        std = torch.sqrt((input - mean).pow(2).mean(dim=(1, 2, 3), keepdim=True) + self.eps)

        normalized_input = (input - mean) / std

        if self.detach_grad:
            rescale, rebias = self.meta1(std.detach()), self.meta2(mean.detach())
        else:
            rescale, rebias = self.meta1(std), self.meta2(mean)

        out = normalized_input * self.weight + self.bias
        return out, rescale, rebias

class MFIB(nn.Module):
    """Multi-dimension Feature Interaction Block from MPMF-Net"""
    def __init__(self, dim=32):
        super().__init__()
        self.scale_h = nn.Parameter(torch.ones((1)), requires_grad=True)
        self.scale_w = nn.Parameter(torch.ones((1)), requires_grad=True)
        self.scale_c = nn.Parameter(torch.ones((1)), requires_grad=True)

        self.norm_u = RLN(dim)
        self.norm_d = RLN(dim)

        self.pconv_qkv_u = nn.Conv2d(dim, dim * 2, 1)
        self.pconv_qkv_d = nn.Conv2d(dim, dim * 2, 1)

    def forward(self, x_u, x_d):
        x_d_norm, rescale_d, bias_d = self.norm_d(x_d)
        x_u_norm, rescale_u, bias_u = self.norm_u(x_u)

        q_u, v_u = self.pconv_qkv_u(x_u_norm).chunk(2, dim=1)
        k_d, v_d = self.pconv_qkv_d(x_d_norm).chunk(2, dim=1)

        q_u_h, q_u_w, q_u_c = q_u.chunk(3, dim=1)
        k_d_h, k_d_w, k_d_c = k_d.chunk(3, dim=1)
        v_u_h, v_u_w, v_u_c = v_u.chunk(3, dim=1)
        v_d_h, v_d_w, v_d_c = v_d.chunk(3, dim=1)

        # h dimension
        q_u_h = q_u_h.permute(0, 3, 2, 1)
        k_d_h = k_d_h.permute(0, 3, 1, 2)
        v_u_h = v_u_h.permute(0, 3, 2, 1)
        v_d_h = v_d_h.permute(0, 3, 2, 1)
        attn_h = torch.matmul(q_u_h, k_d_h) * self.scale_h
        x_d2u_h = torch.matmul(torch.softmax(attn_h, dim=-1), v_d_h)
        x_u2d_h = torch.matmul(torch.softmax(attn_h.transpose(-1, -2), dim=-1), v_u_h)

        # w dimension
        q_u_w = q_u_w.permute(0, 2, 3, 1)
        k_d_w = k_d_w.permute(0, 2, 1, 3)
        v_u_w = v_u_w.permute(0, 2, 3, 1)
        v_d_w = v_d_w.permute(0, 2, 3, 1)
        attn_w = torch.matmul(q_u_w, k_d_w) * self.scale_w
        x_d2u_w = torch.matmul(torch.softmax(attn_w, dim=-1), v_d_w)
        x_u2d_w = torch.matmul(torch.softmax(attn_w.transpose(-1, -2), dim=-1), v_u_w)

        # c dimension
        b, c, h, w = q_u_c.shape
        q_u_c = q_u_c.reshape(b, c, h * w)
        k_d_c = k_d_c.reshape(b, c, h * w).permute(0, 2, 1)
        v_u_c = v_u_c.reshape(b, c, h * w)
        v_d_c = v_d_c.reshape(b, c, h * w)
        attn_c = torch.matmul(q_u_c, k_d_c) * self.scale_c
        x_d2u_c = torch.matmul(torch.softmax(attn_c, dim=-1), v_d_c).reshape(b, c, h, w)
        x_u2d_c = torch.matmul(torch.softmax(attn_c.transpose(-1, -2), dim=-1), v_u_c).reshape(b, c, h, w)

        x_d2u = torch.cat([x_d2u_h.permute(0, 3, 2, 1), x_d2u_w.permute(0, 3, 1, 2), x_d2u_c], dim=1)
        x_u2d = torch.cat([x_u2d_h.permute(0, 3, 2, 1), x_u2d_w.permute(0, 3, 1, 2), x_u2d_c], dim=1)

        x_u = x_d2u * rescale_u + bias_u + x_u
        x_d = x_u2d * rescale_d + bias_d + x_d

        return x_u + x_d
